pub mod auth;
pub mod autostart;
pub mod camera;
pub mod commands;
pub mod configuration;
pub mod error;
pub mod recorder;
pub mod session;
pub mod shutdown;
pub mod state;
pub mod storage;
pub mod utils;
pub mod windows;
pub mod encoder;

pub use auth::*;
pub use autostart::*;
pub use camera::*;
pub use commands::{record_screen, start_session, stop_session};
pub use configuration::*;
pub use error::{Error, Result};
pub use recorder::{RecordChannel, RecordCommand};
pub use session::Session;
pub use shutdown::Shutdown;
pub use state::AppState;
pub use storage::{auth_path, config_path, get_storage_path, load, save, save_to_data_path};
pub use utils::*;
pub use windows::*;
